all:
  children:
    proxmox_hosts:
      hosts:
        pm2:
          ansible_host: 172.17.0.4
          ansible_user: soc
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    opnsense:
      hosts:
        opnsense_fw: # uri/api based, no ssh
          ansible_host: 172.17.0.228
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    wazuh:
      children: 
        indexers:
          hosts:
            prox_idx:
        managers:
          hosts:
            prox_idx:
        dashboards:
          hosts:
            prox_dash:
    vmbr10:
      hosts: {}